[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Disable stake tooltip
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if specific_vars and specific_vars.sticker then info_queue[#info_queue+1] = {key = string.lower(specific_vars.sticker)..'_sticker', set = 'Other'} end"
position = "after"
payload = '''
table.remove(info_queue, #info_queue)
'''
match_indent = true